{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.0.aar",
          "url": "navigation-fragment-2.3.0.aar",
          "size": 19314,
          "sha512": "fd6c611ec637b35b6decb596d494d6bcae78582596f6332d6048a3c16cb5a994100c6a56308aa40889494d9a6aebb2100f9688eea3caf02373a8b8f0822c67d3",
          "sha256": "7de48ee336f43bec4c42dcf60a36f57496dc35dc38a72ef1c0e72c3907111bb9",
          "sha1": "cecad104ae2bdf2f5d9e0dee124bce7f695ffac6",
          "md5": "c6f939a3996bbe117787cf8160491220"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.0.aar",
          "url": "navigation-fragment-2.3.0.aar",
          "size": 19314,
          "sha512": "fd6c611ec637b35b6decb596d494d6bcae78582596f6332d6048a3c16cb5a994100c6a56308aa40889494d9a6aebb2100f9688eea3caf02373a8b8f0822c67d3",
          "sha256": "7de48ee336f43bec4c42dcf60a36f57496dc35dc38a72ef1c0e72c3907111bb9",
          "sha1": "cecad104ae2bdf2f5d9e0dee124bce7f695ffac6",
          "md5": "c6f939a3996bbe117787cf8160491220"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.3.0-sources.jar",
          "url": "navigation-fragment-2.3.0-sources.jar",
          "size": 13519,
          "sha512": "a7b754ab9cc7954d126ae2b30f905a6fd1c4ea9bbde736aee284820d4ab11e21a22026f78000ee5e59889f06cdf8a6fcb95512cb07fcf5df075b6522ed51c393",
          "sha256": "422448a3d055ce5eed89fdf46a035d5c3eedb9b6df061f4291cb81885cad6697",
          "sha1": "1b8d55b17ab1f3f2f7571e4882b6f90f58232022",
          "md5": "82cd3e6bb5536d33aa469ae592ffe060"
        }
      ]
    }
  ]
}
