{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.0.aar",
          "url": "navigation-ui-ktx-2.3.0.aar",
          "size": 32260,
          "sha512": "26db496030e9421eef2e96d920553bad4c3e3465870d18e628a02c914007c5caf073f2fb762cdf827b4e007d1799d5ef17275fbc3fa1b56593c276bfb2d1fbac",
          "sha256": "ebffd6886519739980b0abf4f3b319cd40bc7ea23d3406c19999682baf4aa3e1",
          "sha1": "ae6bff1399d2407db068de0c5b7901978e2ca9f0",
          "md5": "0281ee155c1a0042ddd2a9c91d70b438"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.0.aar",
          "url": "navigation-ui-ktx-2.3.0.aar",
          "size": 32260,
          "sha512": "26db496030e9421eef2e96d920553bad4c3e3465870d18e628a02c914007c5caf073f2fb762cdf827b4e007d1799d5ef17275fbc3fa1b56593c276bfb2d1fbac",
          "sha256": "ebffd6886519739980b0abf4f3b319cd40bc7ea23d3406c19999682baf4aa3e1",
          "sha1": "ae6bff1399d2407db068de0c5b7901978e2ca9f0",
          "md5": "0281ee155c1a0042ddd2a9c91d70b438"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.3.0-sources.jar",
          "url": "navigation-ui-ktx-2.3.0-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
