{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.0.aar",
          "url": "navigation-common-2.3.0.aar",
          "size": 56217,
          "sha512": "55fe69e038f4f3dc61aeb56c84b33e0515a875c41ffef7855ba1966339549c774c5bc571941a3646304f63f44fe4d475f107138304c70bc23ecc8de50aa8798e",
          "sha256": "bf8013824a45be07f16ca4c0a909a70c3a0daacdc5de3669e9edabbe5fedf5dd",
          "sha1": "bf918cbb854b3175b234a8fada83efc20a6f6e83",
          "md5": "93e9c432c048afc33279a2bbb18a4e9d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.0.aar",
          "url": "navigation-common-2.3.0.aar",
          "size": 56217,
          "sha512": "55fe69e038f4f3dc61aeb56c84b33e0515a875c41ffef7855ba1966339549c774c5bc571941a3646304f63f44fe4d475f107138304c70bc23ecc8de50aa8798e",
          "sha256": "bf8013824a45be07f16ca4c0a909a70c3a0daacdc5de3669e9edabbe5fedf5dd",
          "sha1": "bf918cbb854b3175b234a8fada83efc20a6f6e83",
          "md5": "93e9c432c048afc33279a2bbb18a4e9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.3.0-sources.jar",
          "url": "navigation-common-2.3.0-sources.jar",
          "size": 35184,
          "sha512": "857997930e6b4fff1f2e3ab0a2a5cf941283b073bd223853c88fbb2be86288d588c47168693f3993e4d4ce026b59fe79b8650edfe3f332c92cd5bbda22539b4b",
          "sha256": "a05ebd437ee49beede1f51b0d2bb38d1ebd4d902553ea3e445beb213940bd4ef",
          "sha1": "0beb9fbe0140b8f849e75de79dec967712251984",
          "md5": "61637f1e1d924ce4b7f13b2c541859e6"
        }
      ]
    }
  ]
}
