{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.0.aar",
          "url": "navigation-runtime-ktx-2.3.0.aar",
          "size": 13227,
          "sha512": "06c7c9003f70757b1dd6499704df9a25b2168b68651c724f4ffc9e198d5ad67f2a39964929c8b4490b9843616314b9f16158f4102ff297ca5ff121bc4ef87c72",
          "sha256": "bed6c6611f4f2f417b918afb052aa21d167167315609afff06bc8d54743102fc",
          "sha1": "f19bb01e6c1891d7995014319a6311f684d3cd24",
          "md5": "0d2455f9e434d46616ccfc191a0a40ef"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.2.0"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.0.aar",
          "url": "navigation-runtime-ktx-2.3.0.aar",
          "size": 13227,
          "sha512": "06c7c9003f70757b1dd6499704df9a25b2168b68651c724f4ffc9e198d5ad67f2a39964929c8b4490b9843616314b9f16158f4102ff297ca5ff121bc4ef87c72",
          "sha256": "bed6c6611f4f2f417b918afb052aa21d167167315609afff06bc8d54743102fc",
          "sha1": "f19bb01e6c1891d7995014319a6311f684d3cd24",
          "md5": "0d2455f9e434d46616ccfc191a0a40ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-ktx-2.3.0-sources.jar",
          "url": "navigation-runtime-ktx-2.3.0-sources.jar",
          "size": 6128,
          "sha512": "f976814e20f825b4f16bf017c59918c3eb42304e8cb934b491431d2cf1e280bceea3a63b255a8ebbfcbb3886fdf26bd2a258e41928747b90eb04075e421ef4df",
          "sha256": "17df0a9cfd3b645ce58d9716f293ffdcfd8f30b60b87dab2a3cf099dddc1e70a",
          "sha1": "4d2da12a557444e5706dd6ca99f059ec099a45de",
          "md5": "fe0b36da8a72a76b3f3e34d30eebbcb2"
        }
      ]
    }
  ]
}
