{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.0.aar",
          "url": "navigation-runtime-2.3.0.aar",
          "size": 47171,
          "sha512": "0735925d5c033c3ec5233f65e92d94b6e62d3ea2d91eb209c625414c7fd1ba75131d1c178e426aa9aa05f6e900da3d4a436a04c33f5291d9f0746697eb555007",
          "sha256": "3d842eb5cba89dd86a56e4032392dec065f2054f93d4a1eb409cc79b48671c50",
          "sha1": "4a7cc171db11d932aa8e36bd698e2eeba71be7c4",
          "md5": "c70888dc59bdfaffe503f6c85b1b5681"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.0.aar",
          "url": "navigation-runtime-2.3.0.aar",
          "size": 47171,
          "sha512": "0735925d5c033c3ec5233f65e92d94b6e62d3ea2d91eb209c625414c7fd1ba75131d1c178e426aa9aa05f6e900da3d4a436a04c33f5291d9f0746697eb555007",
          "sha256": "3d842eb5cba89dd86a56e4032392dec065f2054f93d4a1eb409cc79b48671c50",
          "sha1": "4a7cc171db11d932aa8e36bd698e2eeba71be7c4",
          "md5": "c70888dc59bdfaffe503f6c85b1b5681"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.3.0-sources.jar",
          "url": "navigation-runtime-2.3.0-sources.jar",
          "size": 34805,
          "sha512": "b66063a187978d0c6956bfcfb92251cea4a46e3d63ce5bd1aa196d60be989805af2e8015448c6c940a3065303fa3e26fccf27cc2ea0edc7176bcfeb745b57be9",
          "sha256": "b55e0c43b11d7edb41e52d079c272f66b75a71d40425e893bea3c58063609426",
          "sha1": "ce839850d38bec85312cf861969b4b32222043ba",
          "md5": "1a09e38f8e2b1a7c9d3d12783843800a"
        }
      ]
    }
  ]
}
