{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6592867"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.0.aar",
          "url": "navigation-common-ktx-2.3.0.aar",
          "size": 26400,
          "sha512": "422b8102564e6202bef3d0547da1f259a3139198f62a20685d6db4a14bf9a90787699e15937b9ba479252ee9ee3d96b056f002e35c420e6834dfd188a389658a",
          "sha256": "2b86b75faad0e6bdcc2c356114a94e8faf5ff25a0ec75a08603bb3b073da2490",
          "sha1": "7a18d1153e8c5f3c65bba7d4fae8fb886c0e18b8",
          "md5": "835dfb9499cc95192772a3cea9aadba2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-ktx-2.3.0.aar",
          "url": "navigation-common-ktx-2.3.0.aar",
          "size": 26400,
          "sha512": "422b8102564e6202bef3d0547da1f259a3139198f62a20685d6db4a14bf9a90787699e15937b9ba479252ee9ee3d96b056f002e35c420e6834dfd188a389658a",
          "sha256": "2b86b75faad0e6bdcc2c356114a94e8faf5ff25a0ec75a08603bb3b073da2490",
          "sha1": "7a18d1153e8c5f3c65bba7d4fae8fb886c0e18b8",
          "md5": "835dfb9499cc95192772a3cea9aadba2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-ktx-2.3.0-sources.jar",
          "url": "navigation-common-ktx-2.3.0-sources.jar",
          "size": 9270,
          "sha512": "2e660b763af1be2ce6c7a11a357707f4b2661e1d087d7cd0f5b7d3ea35d274ed1e7be631eef53f23c25dac96233c22a2b88f801d44d276d15f50fe873cc9f0bb",
          "sha256": "3785b406ae010b5b2080a61ac30f34473414c7b49bd07f0c0ade32ab204c931a",
          "sha1": "1a3ce7c2b9dcc97c1d25ef6ab8e016b5a76de983",
          "md5": "7a3b42155cd6aca62a286819294a8545"
        }
      ]
    }
  ]
}
